### ISSUE TITLE
openwrt router no AP

### ISSUE THREAD

**Issue by mmycjguo** [rmoesbergen/openwrt-ha-device-tracker#41]
My OPENWRT router and AP are separate; how should I fill in the 'interfaces' parameter, and the command 'ubus list hostapd.*' is not working

**Comment by rmoesbergen** [comment]
Hi @mmycjguo , You'll need to run this script on the device that has the WiFi interfaces, so that would be your access point. If it's running OpenWrt, this script and the ubus list hostapd.* command should work there.
