### ISSUE TITLE
Error in sample config

### ISSUE THREAD

**Issue by andreid1303** [rmoesbergen/openwrt-ha-device-tracker#45]
There is a space in sample config that prevent service to run:

`-"hass_token" : "<Home Assistant REST API Bearer Token>"`
`+"hass_token": "<Home Assistant REST API Bearer Token>"`

**Comment by rmoesbergen** [comment]
Hi @andreid1303 , thanks for the report. Although the space shouldn't be there, it doesn't stop the program from working: it's still valid JSON (I just tested this on my device). Do you get an exception when your configuration is invalid?

**Comment by rmoesbergen** [comment]
Readme updated
